[Header] 2017-04-20 15:13:52,882 [1] INFO  LogEx.ConsoleDemo.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 15:13:53,410 [1] DEBUG LogEx.ConsoleDemo.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 15:13:53,497 [1] INFO  LogEx.ConsoleDemo.LoggingExample [(null)] <(null)> - LogEx.ConsoleDemo.LogMessage.ComplexFanLogMessage
2017-04-20 15:13:53,551 [1] INFO  LogEx.ConsoleDemo.LoggingExample [(null)] <(null)> - LogEx.CommonLogMessage
2017-04-20 15:13:53,626 [1] INFO  LogEx.ConsoleDemo.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 15:13:53,662 [1] INFO  LogEx.ConsoleDemo.AnotherClass [(null)] <(null)> - LogEx.ConsoleDemo.LogMessage.ComplexFanLogMessage
2017-04-20 15:13:53,711 [1] INFO  LogEx.ConsoleDemo.AnotherClass [(null)] <(null)> - LogEx.ConsoleDemo.LogMessage.ComplexFanLogMessage
2017-04-20 15:13:53,933 [1] ERROR LogEx.ConsoleDemo.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 LogEx.ConsoleDemo.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\demos\LogEx.ConsoleDemo\LoggingExample.cs:行号 83
   在 LogEx.ConsoleDemo.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\demos\LogEx.ConsoleDemo\LoggingExample.cs:行号 90
   --- 内部异常堆栈跟踪的结尾 ---
   在 LogEx.ConsoleDemo.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\demos\LogEx.ConsoleDemo\LoggingExample.cs:行号 94
   在 LogEx.ConsoleDemo.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\demos\LogEx.ConsoleDemo\LoggingExample.cs:行号 78
   在 LogEx.ConsoleDemo.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\demos\LogEx.ConsoleDemo\LoggingExample.cs:行号 44
2017-04-20 15:13:54,012 [1] ERROR LogEx.ConsoleDemo.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 15:13:54,198 [1] WARN  LogEx.ConsoleDemo.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 15:13:54,257 [1] WARN  LogEx.ConsoleDemo.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 15:13:54,345 [1] WARN  LogEx.ConsoleDemo.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 15:13:54,406 [1] INFO  LogEx.ConsoleDemo.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer] [Header] 2017-04-20 15:14:18,020 [1] INFO  LogEx.ConsoleDemo.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 15:14:19,900 [1] DEBUG LogEx.ConsoleDemo.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 15:14:22,836 [1] INFO  LogEx.ConsoleDemo.LoggingExample [(null)] <(null)> - LogEx.ConsoleDemo.LogMessage.ComplexFanLogMessage
2017-04-20 15:14:22,970 [1] INFO  LogEx.ConsoleDemo.LoggingExample [(null)] <(null)> - LogEx.CommonLogMessage
2017-04-20 15:14:23,398 [1] INFO  LogEx.ConsoleDemo.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 15:14:23,526 [1] INFO  LogEx.ConsoleDemo.AnotherClass [(null)] <(null)> - LogEx.ConsoleDemo.LogMessage.ComplexFanLogMessage
2017-04-20 15:14:23,561 [1] INFO  LogEx.ConsoleDemo.AnotherClass [(null)] <(null)> - LogEx.ConsoleDemo.LogMessage.ComplexFanLogMessage
2017-04-20 15:14:23,793 [1] ERROR LogEx.ConsoleDemo.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 LogEx.ConsoleDemo.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\demos\LogEx.ConsoleDemo\LoggingExample.cs:行号 83
   在 LogEx.ConsoleDemo.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\demos\LogEx.ConsoleDemo\LoggingExample.cs:行号 90
   --- 内部异常堆栈跟踪的结尾 ---
   在 LogEx.ConsoleDemo.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\demos\LogEx.ConsoleDemo\LoggingExample.cs:行号 94
   在 LogEx.ConsoleDemo.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\demos\LogEx.ConsoleDemo\LoggingExample.cs:行号 78
   在 LogEx.ConsoleDemo.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\demos\LogEx.ConsoleDemo\LoggingExample.cs:行号 44
2017-04-20 15:14:23,881 [1] ERROR LogEx.ConsoleDemo.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 15:14:23,949 [1] WARN  LogEx.ConsoleDemo.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 15:14:23,995 [1] WARN  LogEx.ConsoleDemo.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 15:14:24,040 [1] WARN  LogEx.ConsoleDemo.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 15:14:24,072 [1] INFO  LogEx.ConsoleDemo.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer] [Header] 2017-04-20 16:36:27,214 [1] INFO  LogEx.ConsoleDemo.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 16:36:28,874 [1] DEBUG LogEx.ConsoleDemo.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 16:36:29,079 [1] INFO  LogEx.ConsoleDemo.LoggingExample [(null)] <(null)> - LogEx.ConsoleDemo.LogMessage.ComplexFanLogMessage
2017-04-20 16:36:29,348 [1] INFO  LogEx.ConsoleDemo.LoggingExample [(null)] <(null)> - LogEx.CommonLogMessage
2017-04-20 16:36:29,480 [1] INFO  LogEx.ConsoleDemo.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 16:36:29,519 [1] INFO  LogEx.ConsoleDemo.AnotherClass [(null)] <(null)> - LogEx.ConsoleDemo.LogMessage.ComplexFanLogMessage
2017-04-20 16:36:29,568 [1] INFO  LogEx.ConsoleDemo.AnotherClass [(null)] <(null)> - LogEx.ConsoleDemo.LogMessage.ComplexFanLogMessage
2017-04-20 16:36:29,808 [1] ERROR LogEx.ConsoleDemo.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 LogEx.ConsoleDemo.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\demos\LogEx.ConsoleDemo\LoggingExample.cs:行号 83
   在 LogEx.ConsoleDemo.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\demos\LogEx.ConsoleDemo\LoggingExample.cs:行号 90
   --- 内部异常堆栈跟踪的结尾 ---
   在 LogEx.ConsoleDemo.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\demos\LogEx.ConsoleDemo\LoggingExample.cs:行号 94
   在 LogEx.ConsoleDemo.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\demos\LogEx.ConsoleDemo\LoggingExample.cs:行号 78
   在 LogEx.ConsoleDemo.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\demos\LogEx.ConsoleDemo\LoggingExample.cs:行号 44
2017-04-20 16:36:29,907 [1] ERROR LogEx.ConsoleDemo.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 16:36:29,954 [1] WARN  LogEx.ConsoleDemo.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 16:36:30,046 [1] WARN  LogEx.ConsoleDemo.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 16:36:30,117 [1] WARN  LogEx.ConsoleDemo.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 16:36:30,155 [1] INFO  LogEx.ConsoleDemo.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer] 