[Header]
2017-04-17 23:11:52,436 [10] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-17 23:11:52,597 [10] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-17 23:11:52,827 [10] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 97
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 104
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 110
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 92
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 58
2017-04-17 23:11:52,885 [10] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-17 23:11:52,913 [10] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-17 23:11:52,919 [10] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-17 23:11:52,948 [10] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-17 23:11:52,967 [10] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-17 23:13:12,898 [10] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-17 23:13:13,053 [10] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-17 23:13:13,104 [10] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 97
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 104
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 110
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 92
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 58
2017-04-17 23:13:13,139 [10] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-17 23:13:13,181 [10] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-17 23:13:13,185 [10] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-17 23:13:13,206 [10] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-17 23:13:13,228 [10] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Header]
2017-04-17 23:14:41,458 [10] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-17 23:14:41,618 [10] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-17 23:14:41,685 [10] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 97
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 104
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 110
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 92
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 58
2017-04-17 23:14:41,722 [10] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-17 23:14:41,754 [10] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-17 23:14:41,759 [10] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-17 23:14:41,782 [10] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-17 23:14:41,803 [10] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-17 23:17:23,084 [10] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-17 23:17:23,281 [10] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-17 23:17:23,342 [10] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 97
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 104
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 110
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 92
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 58
2017-04-17 23:17:50,427 [10] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-17 23:17:50,502 [10] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-17 23:17:50,507 [10] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-17 23:17:50,533 [10] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-17 23:17:50,560 [10] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-17 23:24:08,506 [10] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-17 23:24:08,859 [10] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-17 23:24:08,921 [10] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 97
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 104
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 110
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 92
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 58
2017-04-17 23:24:08,955 [10] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-17 23:24:08,996 [10] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-17 23:24:09,004 [10] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-17 23:24:09,059 [10] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-17 23:24:21,138 [10] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-17 23:28:15,146 [10] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-17 23:28:15,636 [10] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-17 23:28:15,728 [10] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 97
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 104
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 110
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 92
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 58
2017-04-17 23:28:15,780 [10] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-17 23:28:15,832 [10] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-17 23:28:15,844 [10] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-17 23:28:15,900 [10] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-17 23:28:15,932 [10] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-18 00:14:25,454 [9] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-18 00:14:32,333 [9] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-18 00:14:32,412 [9] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 97
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 104
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 110
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 92
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 58
2017-04-18 00:14:32,475 [9] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-18 00:14:32,541 [9] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-18 00:14:32,577 [9] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-18 00:14:32,640 [9] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-18 00:14:32,709 [9] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Header]
2017-04-18 00:15:50,359 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-18 00:15:50,630 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-18 00:15:53,421 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 97
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 104
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 110
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 92
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 58
2017-04-18 00:15:53,503 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-18 00:15:53,555 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-18 00:15:53,563 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-18 00:15:53,596 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-18 00:15:53,627 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Header]
2017-04-18 11:31:06,057 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-18 11:31:06,600 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-18 11:31:07,596 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
2017-04-18 11:31:07,628 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-18 11:31:07,668 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-18 11:31:07,677 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-18 11:31:07,703 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-18 11:31:07,730 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-18 11:33:18,436 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-18 11:33:20,746 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-18 11:33:21,035 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
2017-04-18 11:33:21,282 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-18 11:33:21,535 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-18 11:33:21,707 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-18 11:33:21,886 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-18 11:33:22,070 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-18 11:33:29,405 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-18 11:33:31,127 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-18 11:33:31,351 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
2017-04-18 11:33:31,585 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-18 11:33:31,879 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-18 11:33:32,134 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-18 11:33:32,311 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-18 11:33:32,491 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Header]
2017-04-18 11:58:56,392 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-18 11:58:58,796 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-18 11:58:58,831 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.LogMessage
2017-04-18 11:58:59,590 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
2017-04-18 11:58:59,657 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-18 11:58:59,690 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-18 11:58:59,698 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-18 11:58:59,734 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-18 11:58:59,757 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Header]
2017-04-18 12:46:35,287 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-18 12:46:35,521 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-18 12:46:35,553 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.LogMessage
2017-04-18 12:46:35,602 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
2017-04-18 12:46:35,672 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-18 12:46:35,712 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-18 12:46:35,727 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-18 12:46:35,779 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-18 12:46:35,817 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-18 12:47:03,933 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-18 12:47:04,160 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-18 12:47:04,198 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.LogMessage
2017-04-18 12:47:04,249 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
2017-04-18 12:47:04,300 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-18 12:47:04,339 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-18 12:47:04,354 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-18 12:47:04,392 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-18 12:47:04,427 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-18 12:47:42,040 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-18 12:47:42,247 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-18 12:47:42,286 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.LogMessage
2017-04-18 12:47:42,344 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
2017-04-18 12:47:42,396 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-18 12:47:42,440 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-18 12:47:42,463 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-18 12:47:42,497 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-18 12:47:42,534 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-18 12:47:58,721 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-18 12:47:58,924 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-18 12:47:58,966 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.LogMessage
2017-04-18 12:47:59,013 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
2017-04-18 12:47:59,067 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-18 12:47:59,114 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-18 12:47:59,129 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-18 12:47:59,163 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-18 12:47:59,198 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-18 12:49:54,730 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-18 12:49:54,953 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-18 12:49:54,989 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.LogMessage
2017-04-18 12:49:55,781 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
2017-04-18 12:49:55,829 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-18 12:49:55,865 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-18 12:49:55,872 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-18 12:49:55,897 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-18 12:49:55,923 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-18 12:50:04,052 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-18 12:50:04,726 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-18 12:50:04,765 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.LogMessage
2017-04-18 12:50:05,629 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
2017-04-18 12:50:05,681 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-18 12:50:05,717 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-18 12:50:05,724 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-18 12:50:05,756 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-18 12:50:05,782 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-18 13:39:21,553 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-18 13:39:21,850 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-18 13:39:21,885 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.UpdateLogMessage
2017-04-18 13:39:23,167 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
2017-04-18 13:39:23,281 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-18 13:39:23,321 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-18 13:39:23,329 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-18 13:39:23,360 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-18 13:39:23,391 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-18 13:40:00,239 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-18 13:40:00,434 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-18 13:40:00,468 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.UpdateLogMessage
2017-04-18 13:40:01,358 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
2017-04-18 13:40:01,425 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-18 13:40:01,476 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-18 13:40:01,484 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-18 13:40:01,520 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-18 13:40:01,563 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Header]
2017-04-18 13:42:13,459 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-18 13:42:13,606 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-18 13:42:13,630 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.UpdateLogMessage
2017-04-18 13:42:14,408 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
2017-04-18 13:42:14,469 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-18 13:42:14,505 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-18 13:42:14,508 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-18 13:42:14,529 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-18 13:42:14,552 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Header]
2017-04-18 13:42:57,675 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-18 13:42:58,278 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-18 13:42:58,313 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.UpdateLogMessage
2017-04-18 13:42:59,082 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
2017-04-18 13:42:59,135 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-18 13:42:59,174 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-18 13:42:59,184 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-18 13:42:59,219 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-18 13:42:59,246 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Header]
2017-04-18 16:12:26,393 [10] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-18 16:12:26,792 [10] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-18 16:12:26,946 [10] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.UpdateLogMessage
2017-04-18 16:12:27,001 [10] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
2017-04-18 16:12:27,100 [10] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-18 16:12:27,143 [10] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-18 16:12:27,151 [10] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-18 16:12:27,184 [10] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-18 16:12:27,218 [10] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-19 20:44:19,361 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-19 20:44:34,253 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-19 20:44:34,302 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.UpdateLogMessage
2017-04-19 20:44:34,643 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
2017-04-19 20:44:34,726 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-19 20:44:34,829 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-19 20:44:34,911 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-19 20:44:34,944 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-19 20:44:34,977 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-19 20:45:00,262 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-19 20:45:00,810 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-19 20:45:00,883 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.UpdateLogMessage
2017-04-19 20:45:01,227 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
2017-04-19 20:45:01,453 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-19 20:45:01,684 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-19 20:45:01,919 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-19 20:45:02,197 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-19 20:45:02,303 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 09:18:34,365 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 09:19:00,114 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 09:19:00,179 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.UpdateLogMessage
2017-04-20 09:19:00,307 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
2017-04-20 09:19:00,408 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 09:19:00,464 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 09:19:00,480 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 09:19:00,520 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 09:19:00,562 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Header]
2017-04-20 09:50:04,295 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 09:50:04,783 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 09:50:04,823 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.UpdateLogMessage
2017-04-20 09:50:05,772 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
2017-04-20 09:50:05,890 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 09:50:05,977 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 09:50:05,990 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 09:50:06,037 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 09:50:06,099 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 09:51:27,001 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 09:51:27,713 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 09:51:27,818 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.UpdateLogMessage
2017-04-20 09:51:28,216 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
2017-04-20 09:51:28,337 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 09:51:28,395 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 09:51:28,415 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 09:51:28,489 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 09:51:28,547 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 10:04:08,001 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 10:04:10,310 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 10:04:10,380 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.UpdateLogMessage
2017-04-20 10:04:10,486 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 10:04:10,624 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 10:04:10,674 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 10:04:10,695 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 10:04:10,740 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 10:04:10,803 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Header]
2017-04-20 10:06:25,426 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 10:06:27,672 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 10:06:27,723 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.UpdateLogMessage
2017-04-20 10:06:27,863 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 10:06:34,122 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 10:06:34,276 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 10:06:34,375 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 10:06:34,438 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 10:06:34,485 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 10:08:43,225 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 10:08:45,458 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 10:08:45,594 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.UpdateLogMessage
2017-04-20 10:09:01,866 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 10:09:02,093 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 10:09:02,225 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 10:09:02,241 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 10:09:02,319 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 10:09:02,390 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 10:11:43,719 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 10:11:44,481 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 10:11:44,542 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.UpdateLogMessage
2017-04-20 10:11:44,875 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 10:11:44,975 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 10:11:45,075 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 10:11:45,099 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 10:11:45,169 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 10:11:45,219 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 10:13:19,842 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 10:13:20,236 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 10:13:20,543 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.UpdateLogMessage
[Header]
2017-04-20 10:14:51,815 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 10:14:52,889 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 10:14:52,969 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.UpdateLogMessage
2017-04-20 10:14:56,886 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 10:14:56,918 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.UpdateLogMessage
2017-04-20 10:14:59,442 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 10:14:59,568 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 10:14:59,733 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 10:14:59,757 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 10:14:59,938 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 10:15:00,059 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 10:17:36,569 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 10:17:37,709 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 10:17:37,975 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.UpdateLogMessage
2017-04-20 10:17:38,005 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 10:17:38,029 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.UpdateLogMessage
2017-04-20 10:17:38,069 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.UpdateLogMessage
2017-04-20 10:17:38,175 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 10:17:38,381 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 10:17:38,428 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 10:17:38,444 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 10:17:38,491 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 10:17:38,565 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Header]
2017-04-20 12:51:16,382 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 12:51:17,087 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 12:51:17,809 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 12:51:17,846 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 12:51:17,876 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 12:51:17,903 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 12:51:18,008 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 12:51:18,090 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 12:51:18,150 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 12:51:18,213 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 12:51:18,271 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 12:51:18,323 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Header]
2017-04-20 12:53:32,313 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 12:53:32,915 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 12:53:33,020 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 12:53:33,075 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 12:53:33,106 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 12:53:33,186 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 12:53:33,237 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 12:53:33,315 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 12:53:33,433 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 12:53:33,465 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 12:53:33,621 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 12:53:33,715 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 12:53:48,707 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 12:53:49,201 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 12:53:49,263 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 12:53:49,334 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 12:53:49,365 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 12:53:49,395 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 12:53:49,467 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 12:53:49,557 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 12:53:49,629 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 12:53:49,659 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 12:53:49,713 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 12:53:49,899 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Header]
2017-04-20 13:10:36,850 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 13:10:37,408 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 13:10:37,486 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:10:37,533 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 13:10:37,567 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:10:37,641 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:10:37,865 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 13:10:37,960 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 13:10:38,578 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 13:10:38,674 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 13:10:38,736 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 13:10:38,811 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Header]
2017-04-20 13:13:12,389 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 13:13:12,789 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 13:13:12,851 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:13:12,882 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 13:13:12,898 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:13:12,949 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:13:12,990 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 13:13:13,043 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 13:13:13,152 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 13:13:13,174 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 13:13:13,235 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 13:13:13,267 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 13:13:27,950 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 13:13:28,460 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 13:13:28,540 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:13:28,564 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 13:13:28,583 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:13:28,642 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:13:28,710 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 13:13:28,753 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 13:13:28,805 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 13:13:28,835 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 13:13:28,901 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 13:13:28,947 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 13:18:16,427 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 13:18:17,219 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 13:18:17,313 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:18:17,352 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 13:18:17,376 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:18:17,401 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:18:17,544 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 13:18:17,627 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 13:18:17,783 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 13:18:17,803 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 13:18:17,853 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 13:18:17,897 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 13:26:11,113 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 13:26:11,756 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 13:26:11,931 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:26:11,956 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 13:26:12,027 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:26:12,046 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:26:12,095 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 13:26:12,145 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 13:26:12,226 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 13:26:12,254 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 13:26:12,346 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 13:26:12,394 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 13:26:25,500 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 13:26:28,272 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 13:26:28,557 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:26:28,824 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 13:26:29,060 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:26:29,213 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:26:29,307 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 13:26:29,360 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 13:26:29,420 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 13:26:29,440 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 13:26:29,527 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 13:26:29,569 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Header]
2017-04-20 13:29:23,094 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 13:29:24,415 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 13:29:24,567 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:29:24,661 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 13:29:24,786 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:29:24,821 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:29:24,874 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 13:29:24,980 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 13:29:25,050 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 13:29:25,070 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 13:29:25,149 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 13:29:25,193 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 13:29:46,622 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 13:29:47,121 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 13:29:47,169 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:29:47,191 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 13:29:47,208 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:29:47,224 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:29:47,338 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 13:29:47,412 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 13:29:47,496 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 13:29:47,522 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 13:29:47,569 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 13:29:47,638 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 13:30:24,830 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 13:30:25,675 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 13:30:25,772 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:30:25,818 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 13:30:25,848 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:30:25,866 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:30:26,107 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 13:30:26,232 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 13:30:26,293 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 13:30:26,319 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 13:30:26,396 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 13:30:26,585 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 13:37:19,961 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 13:37:20,387 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 13:37:20,442 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:37:20,458 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 13:37:20,468 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:37:20,481 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:37:20,687 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 13:37:20,727 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 13:37:20,771 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 13:37:20,782 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 13:37:20,816 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 13:37:20,867 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 13:37:35,197 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 13:37:35,733 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 13:37:35,917 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:37:35,935 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 13:37:35,946 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:37:35,955 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:37:36,056 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 13:37:36,097 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 13:37:36,140 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 13:37:36,153 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 13:37:36,188 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 13:37:36,230 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 13:39:17,883 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 13:39:18,447 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 13:39:18,502 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:39:18,522 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 13:39:18,536 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:39:18,549 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:39:18,596 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 13:39:18,638 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 13:39:18,715 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 13:39:18,731 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 13:39:18,770 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 13:39:18,808 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 13:43:47,426 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 13:43:48,792 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 13:43:49,162 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:43:49,369 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 13:43:49,617 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:43:49,664 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:43:50,088 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 13:43:50,138 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 13:43:50,185 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 13:43:50,197 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 13:43:50,235 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 13:43:50,281 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 13:44:06,946 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 13:44:07,684 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 13:44:07,724 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:44:07,746 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 13:44:07,758 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:44:07,772 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:44:08,202 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 13:44:08,400 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 13:44:08,487 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 13:44:08,510 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 13:44:08,556 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 13:44:08,691 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 13:44:56,057 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 13:44:56,851 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 13:44:57,069 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:44:57,132 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 13:44:57,163 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:44:57,195 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:44:57,440 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 13:44:57,565 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 13:44:57,651 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 13:44:57,675 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 13:44:58,101 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 13:44:58,195 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 13:45:58,181 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
[Header]
2017-04-20 13:46:50,691 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 13:46:51,085 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 13:46:51,139 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:46:51,166 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 13:46:51,180 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:46:51,196 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:46:51,251 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 13:46:51,308 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 13:46:51,393 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 13:46:51,423 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 13:46:51,504 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 13:46:51,553 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 13:47:53,032 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 13:47:54,260 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 13:47:54,602 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:47:54,655 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 13:47:54,702 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:47:54,772 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:47:54,960 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 13:47:55,096 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 13:47:55,204 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 13:47:55,298 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 13:47:55,357 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 13:47:55,407 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 13:48:27,491 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 13:48:27,973 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 13:48:28,024 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:48:28,050 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 13:48:28,071 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:48:28,091 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:48:28,164 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 13:48:28,210 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 13:48:28,267 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 13:48:28,296 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 13:48:28,345 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 13:48:28,401 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Header]
2017-04-20 13:48:58,614 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 13:48:59,052 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 13:48:59,141 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:48:59,183 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 13:48:59,201 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:48:59,223 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:48:59,296 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 13:48:59,340 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 13:48:59,413 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 13:48:59,436 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 13:48:59,481 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 13:48:59,535 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 13:49:23,721 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 13:49:24,061 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 13:49:24,140 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:49:24,193 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 13:49:24,210 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:49:24,228 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:49:24,279 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 13:49:24,327 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 13:49:24,379 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 13:49:24,437 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 13:49:24,485 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 13:49:24,528 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Header]
2017-04-20 13:51:15,975 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 13:51:16,980 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 13:51:17,039 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:51:17,123 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 13:51:17,135 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:51:17,149 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:51:17,254 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 13:51:17,331 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 13:51:17,476 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 13:51:17,490 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 13:51:17,582 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 13:51:17,624 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 13:51:31,885 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 13:51:32,208 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 13:51:32,246 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:51:32,265 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 13:51:32,275 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:51:32,285 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:51:32,366 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 13:51:32,402 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 13:51:32,448 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 13:51:32,465 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 13:51:32,499 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 13:51:32,534 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 13:52:37,191 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 13:52:37,595 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 13:52:37,656 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:52:37,685 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 13:52:37,695 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:52:37,706 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:52:37,789 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 13:52:37,829 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 13:52:37,884 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 13:52:37,905 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 13:52:37,938 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 13:52:37,967 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 13:57:09,144 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 13:57:09,779 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 13:57:09,822 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:57:09,839 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 13:57:09,851 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:57:09,861 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:57:09,950 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 13:57:10,011 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 13:57:10,060 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 13:57:10,072 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 13:57:10,108 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 13:57:10,143 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 13:58:51,710 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 13:58:52,357 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 13:58:52,442 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:58:52,464 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 13:58:52,479 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:58:52,495 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:58:52,550 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 13:58:52,608 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 13:58:52,695 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 13:58:52,715 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 13:58:52,762 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 13:58:52,821 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 13:59:55,834 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 13:59:56,899 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 13:59:57,046 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:59:57,170 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 13:59:57,248 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:59:57,299 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:59:57,429 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 13:59:57,648 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 13:59:57,874 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 13:59:57,903 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 13:59:57,986 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 13:59:58,115 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Header]
2017-04-20 14:00:45,092 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 14:00:45,617 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 14:00:45,693 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 14:00:45,750 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 14:00:45,815 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 14:00:45,867 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 14:00:45,889 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 14:00:45,945 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 14:00:46,004 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Header]
2017-04-20 14:05:34,792 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 14:05:35,362 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 14:05:35,468 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 14:05:35,527 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 14:05:35,579 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 14:05:35,632 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 14:05:35,652 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 14:05:35,727 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 14:05:35,770 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Header]
2017-04-20 14:06:57,490 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 14:06:58,501 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 14:06:58,552 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 14:06:58,694 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 14:06:58,751 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 14:06:58,800 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 14:06:58,812 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 14:06:58,863 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 14:06:58,901 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 14:09:12,435 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 14:09:13,464 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 14:09:13,559 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 14:09:13,661 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 14:09:13,729 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 14:09:13,771 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 14:09:13,788 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 14:09:13,835 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 14:09:13,934 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 14:10:16,920 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 14:10:19,313 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 14:10:19,401 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 14:10:19,519 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 14:10:19,630 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 14:10:19,675 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 14:10:19,692 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 14:10:19,736 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 14:10:19,815 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 14:13:00,438 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 14:13:01,586 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 14:13:01,670 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 14:13:01,725 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.CommonLogMessage
2017-04-20 14:13:01,871 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 101
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 108
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 114
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 96
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 62
2017-04-20 14:13:01,985 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 14:13:02,063 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 14:13:02,092 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 14:13:02,182 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 14:13:02,247 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 14:14:33,617 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 14:14:34,183 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 14:14:34,233 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 14:14:34,258 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.CommonLogMessage
2017-04-20 14:14:34,398 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 101
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 108
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 114
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 96
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 62
2017-04-20 14:14:34,449 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 14:14:34,503 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 14:14:34,521 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 14:14:34,568 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 14:14:34,623 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 14:16:46,641 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 14:16:47,621 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 14:16:47,700 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 14:16:47,732 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.CommonLogMessage
2017-04-20 14:16:47,839 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 101
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 108
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 114
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 96
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 62
2017-04-20 14:16:47,938 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 14:16:47,982 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 14:16:47,999 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 14:16:48,040 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 14:16:48,078 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 14:17:43,850 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 14:17:45,204 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 14:17:45,253 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 14:17:45,287 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.CommonLogMessage
2017-04-20 14:17:45,338 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 14:17:45,359 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 14:17:45,411 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 14:17:45,493 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 101
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 108
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 114
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 96
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 62
2017-04-20 14:17:45,559 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 14:17:45,676 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 14:17:45,704 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 14:17:45,923 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 14:17:45,990 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
