[Header]
2017-04-17 23:11:52,436 [10] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-17 23:11:52,597 [10] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-17 23:11:52,827 [10] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 97
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 104
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 110
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 92
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 58
2017-04-17 23:11:52,885 [10] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-17 23:11:52,913 [10] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-17 23:11:52,919 [10] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-17 23:11:52,948 [10] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-17 23:11:52,967 [10] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-17 23:13:12,898 [10] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-17 23:13:13,053 [10] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-17 23:13:13,104 [10] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 97
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 104
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 110
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 92
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 58
2017-04-17 23:13:13,139 [10] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-17 23:13:13,181 [10] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-17 23:13:13,185 [10] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-17 23:13:13,206 [10] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-17 23:13:13,228 [10] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Header]
2017-04-17 23:14:41,458 [10] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-17 23:14:41,618 [10] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-17 23:14:41,685 [10] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 97
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 104
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 110
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 92
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 58
2017-04-17 23:14:41,722 [10] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-17 23:14:41,754 [10] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-17 23:14:41,759 [10] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-17 23:14:41,782 [10] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-17 23:14:41,803 [10] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-17 23:17:23,084 [10] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-17 23:17:23,281 [10] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-17 23:17:23,342 [10] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 97
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 104
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 110
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 92
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 58
2017-04-17 23:17:50,427 [10] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-17 23:17:50,502 [10] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-17 23:17:50,507 [10] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-17 23:17:50,533 [10] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-17 23:17:50,560 [10] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-17 23:24:08,506 [10] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-17 23:24:08,859 [10] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-17 23:24:08,921 [10] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 97
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 104
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 110
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 92
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 58
2017-04-17 23:24:08,955 [10] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-17 23:24:08,996 [10] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-17 23:24:09,004 [10] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-17 23:24:09,059 [10] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-17 23:24:21,138 [10] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-17 23:28:15,146 [10] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-17 23:28:15,636 [10] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-17 23:28:15,728 [10] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 97
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 104
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 110
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 92
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 58
2017-04-17 23:28:15,780 [10] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-17 23:28:15,832 [10] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-17 23:28:15,844 [10] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-17 23:28:15,900 [10] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-17 23:28:15,932 [10] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-18 00:14:25,454 [9] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-18 00:14:32,333 [9] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-18 00:14:32,412 [9] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 97
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 104
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 110
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 92
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 58
2017-04-18 00:14:32,475 [9] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-18 00:14:32,541 [9] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-18 00:14:32,577 [9] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-18 00:14:32,640 [9] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-18 00:14:32,709 [9] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Header]
2017-04-18 00:15:50,359 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-18 00:15:50,630 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-18 00:15:53,421 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 97
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 104
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 110
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 92
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\log4net-2.0.8\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 58
2017-04-18 00:15:53,503 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-18 00:15:53,555 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-18 00:15:53,563 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-18 00:15:53,596 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-18 00:15:53,627 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Header]
2017-04-18 11:31:06,057 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-18 11:31:06,600 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-18 11:31:07,596 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
2017-04-18 11:31:07,628 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-18 11:31:07,668 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-18 11:31:07,677 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-18 11:31:07,703 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-18 11:31:07,730 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-18 11:33:18,436 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-18 11:33:20,746 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-18 11:33:21,035 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
2017-04-18 11:33:21,282 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-18 11:33:21,535 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-18 11:33:21,707 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-18 11:33:21,886 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-18 11:33:22,070 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-18 11:33:29,405 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-18 11:33:31,127 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-18 11:33:31,351 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
2017-04-18 11:33:31,585 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-18 11:33:31,879 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-18 11:33:32,134 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-18 11:33:32,311 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-18 11:33:32,491 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Header]
2017-04-18 11:58:56,392 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-18 11:58:58,796 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-18 11:58:58,831 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.LogMessage
2017-04-18 11:58:59,590 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
2017-04-18 11:58:59,657 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-18 11:58:59,690 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-18 11:58:59,698 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-18 11:58:59,734 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-18 11:58:59,757 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Header]
2017-04-18 12:46:35,287 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-18 12:46:35,521 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-18 12:46:35,553 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.LogMessage
2017-04-18 12:46:35,602 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
2017-04-18 12:46:35,672 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-18 12:46:35,712 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-18 12:46:35,727 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-18 12:46:35,779 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-18 12:46:35,817 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-18 12:47:03,933 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-18 12:47:04,160 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-18 12:47:04,198 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.LogMessage
2017-04-18 12:47:04,249 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
2017-04-18 12:47:04,300 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-18 12:47:04,339 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-18 12:47:04,354 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-18 12:47:04,392 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-18 12:47:04,427 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-18 12:47:42,040 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-18 12:47:42,247 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-18 12:47:42,286 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.LogMessage
2017-04-18 12:47:42,344 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
2017-04-18 12:47:42,396 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-18 12:47:42,440 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-18 12:47:42,463 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-18 12:47:42,497 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-18 12:47:42,534 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-18 12:47:58,721 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-18 12:47:58,924 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-18 12:47:58,966 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.LogMessage
2017-04-18 12:47:59,013 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
2017-04-18 12:47:59,067 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-18 12:47:59,114 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-18 12:47:59,129 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-18 12:47:59,163 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-18 12:47:59,198 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-18 12:49:54,730 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-18 12:49:54,953 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-18 12:49:54,989 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.LogMessage
2017-04-18 12:49:55,781 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
2017-04-18 12:49:55,829 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-18 12:49:55,865 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-18 12:49:55,872 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-18 12:49:55,897 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-18 12:49:55,923 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-18 12:50:04,052 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-18 12:50:04,726 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-18 12:50:04,765 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.LogMessage
2017-04-18 12:50:05,629 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
2017-04-18 12:50:05,681 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-18 12:50:05,717 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-18 12:50:05,724 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-18 12:50:05,756 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-18 12:50:05,782 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-18 13:39:21,553 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-18 13:39:21,850 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-18 13:39:21,885 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.UpdateLogMessage
2017-04-18 13:39:23,167 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
2017-04-18 13:39:23,281 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-18 13:39:23,321 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-18 13:39:23,329 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-18 13:39:23,360 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-18 13:39:23,391 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-18 13:40:00,239 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-18 13:40:00,434 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-18 13:40:00,468 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.UpdateLogMessage
2017-04-18 13:40:01,358 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
2017-04-18 13:40:01,425 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-18 13:40:01,476 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-18 13:40:01,484 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-18 13:40:01,520 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-18 13:40:01,563 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Header]
2017-04-18 13:42:13,459 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-18 13:42:13,606 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-18 13:42:13,630 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.UpdateLogMessage
2017-04-18 13:42:14,408 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
2017-04-18 13:42:14,469 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-18 13:42:14,505 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-18 13:42:14,508 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-18 13:42:14,529 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-18 13:42:14,552 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Header]
2017-04-18 13:42:57,675 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-18 13:42:58,278 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-18 13:42:58,313 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.UpdateLogMessage
2017-04-18 13:42:59,082 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
2017-04-18 13:42:59,135 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-18 13:42:59,174 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-18 13:42:59,184 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-18 13:42:59,219 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-18 13:42:59,246 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Header]
2017-04-18 16:12:26,393 [10] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-18 16:12:26,792 [10] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-18 16:12:26,946 [10] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.UpdateLogMessage
2017-04-18 16:12:27,001 [10] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
2017-04-18 16:12:27,100 [10] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-18 16:12:27,143 [10] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-18 16:12:27,151 [10] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-18 16:12:27,184 [10] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-18 16:12:27,218 [10] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-19 20:44:19,361 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-19 20:44:34,253 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-19 20:44:34,302 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.UpdateLogMessage
2017-04-19 20:44:34,643 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
2017-04-19 20:44:34,726 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-19 20:44:34,829 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-19 20:44:34,911 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-19 20:44:34,944 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-19 20:44:34,977 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-19 20:45:00,262 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-19 20:45:00,810 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-19 20:45:00,883 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.UpdateLogMessage
2017-04-19 20:45:01,227 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
2017-04-19 20:45:01,453 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-19 20:45:01,684 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-19 20:45:01,919 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-19 20:45:02,197 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-19 20:45:02,303 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 09:18:34,365 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 09:19:00,114 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 09:19:00,179 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.UpdateLogMessage
2017-04-20 09:19:00,307 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
2017-04-20 09:19:00,408 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 09:19:00,464 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 09:19:00,480 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 09:19:00,520 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 09:19:00,562 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Header]
2017-04-20 09:50:04,295 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 09:50:04,783 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 09:50:04,823 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.UpdateLogMessage
2017-04-20 09:50:05,772 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
2017-04-20 09:50:05,890 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 09:50:05,977 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 09:50:05,990 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 09:50:06,037 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 09:50:06,099 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 09:51:27,001 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 09:51:27,713 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 09:51:27,818 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.UpdateLogMessage
2017-04-20 09:51:28,216 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
2017-04-20 09:51:28,337 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 09:51:28,395 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 09:51:28,415 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 09:51:28,489 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 09:51:28,547 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 10:04:08,001 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 10:04:10,310 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 10:04:10,380 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.UpdateLogMessage
2017-04-20 10:04:10,486 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 10:04:10,624 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 10:04:10,674 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 10:04:10,695 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 10:04:10,740 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 10:04:10,803 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Header]
2017-04-20 10:06:25,426 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 10:06:27,672 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 10:06:27,723 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.UpdateLogMessage
2017-04-20 10:06:27,863 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 10:06:34,122 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 10:06:34,276 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 10:06:34,375 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 10:06:34,438 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 10:06:34,485 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 10:08:43,225 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 10:08:45,458 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 10:08:45,594 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.UpdateLogMessage
2017-04-20 10:09:01,866 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 10:09:02,093 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 10:09:02,225 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 10:09:02,241 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 10:09:02,319 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 10:09:02,390 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 10:11:43,719 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 10:11:44,481 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 10:11:44,542 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.UpdateLogMessage
2017-04-20 10:11:44,875 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 10:11:44,975 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 10:11:45,075 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 10:11:45,099 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 10:11:45,169 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 10:11:45,219 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 10:13:19,842 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 10:13:20,236 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 10:13:20,543 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.UpdateLogMessage
[Header]
2017-04-20 10:14:51,815 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 10:14:52,889 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 10:14:52,969 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.UpdateLogMessage
2017-04-20 10:14:56,886 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 10:14:56,918 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.UpdateLogMessage
2017-04-20 10:14:59,442 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 10:14:59,568 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 10:14:59,733 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 10:14:59,757 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 10:14:59,938 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 10:15:00,059 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 10:17:36,569 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 10:17:37,709 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 10:17:37,975 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.UpdateLogMessage
2017-04-20 10:17:38,005 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 10:17:38,029 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.UpdateLogMessage
2017-04-20 10:17:38,069 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.UpdateLogMessage
2017-04-20 10:17:38,175 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 10:17:38,381 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 10:17:38,428 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 10:17:38,444 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 10:17:38,491 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 10:17:38,565 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Header]
2017-04-20 12:51:16,382 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 12:51:17,087 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 12:51:17,809 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 12:51:17,846 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 12:51:17,876 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 12:51:17,903 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 12:51:18,008 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 12:51:18,090 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 12:51:18,150 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 12:51:18,213 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 12:51:18,271 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 12:51:18,323 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Header]
2017-04-20 12:53:32,313 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 12:53:32,915 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 12:53:33,020 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 12:53:33,075 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 12:53:33,106 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 12:53:33,186 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 12:53:33,237 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 12:53:33,315 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 12:53:33,433 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 12:53:33,465 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 12:53:33,621 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 12:53:33,715 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Footer]
[Header]
2017-04-20 12:53:48,707 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 12:53:49,201 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 12:53:49,263 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 12:53:49,334 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 12:53:49,365 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 12:53:49,395 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 12:53:49,467 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 12:53:49,557 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 12:53:49,629 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 12:53:49,659 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 12:53:49,713 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 12:53:49,899 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
[Header]
2017-04-20 13:10:36,850 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - Application [ConsoleApp] Start
2017-04-20 13:10:37,408 [1] DEBUG ConsoleApp.LoggingExample [(null)] <(null)> - This is a debug message
2017-04-20 13:10:37,486 [1] INFO  ConsoleApp.LoggingExample [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:10:37,533 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - 这是另外一个Class
2017-04-20 13:10:37,567 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:10:37,641 [1] INFO  ConsoleApp.AnotherClass [(null)] <(null)> - ConsoleApp.LogEx.ComplexFanLogMessage
2017-04-20 13:10:37,865 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 100
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 107
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 95
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 61
2017-04-20 13:10:37,960 [1] ERROR ConsoleApp.LoggingExample [(null)] <(null)> - Hey this is an error!
2017-04-20 13:10:38,578 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <(null)> - This should have an NDC message
2017-04-20 13:10:38,674 [1] WARN  ConsoleApp.LoggingExample [NDC_Message] <auth-none> - This should have an MDC message for the key 'auth'
2017-04-20 13:10:38,736 [1] WARN  ConsoleApp.LoggingExample [(null)] <auth-none> - See the NDC has been popped of! The MDC 'auth' key is still with us.
2017-04-20 13:10:38,811 [1] INFO  ConsoleApp.LoggingExample [(null)] <auth-none> - Application [ConsoleApp] End
