[Header] 2017-04-20 15:01:12,080 [1] INFO  ConsoleApp.LoggingExample [(null)] - LogEx.CommonLogMessage
2017-04-20 15:01:12,661 [1] ERROR ConsoleApp.LoggingExample [(null)] - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 102
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 109
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 113
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 97
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 63
[Footer] 