[Header]
2017-04-20 14:17:45,493 [1] ERROR ConsoleApp.LoggingExample [(null)] - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 101
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 108
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 114
   在 ConsoleApp.LoggingExample.Bar() 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 96
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 C:\D\work\实验室\Log4Net-Extension\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 62
[Footer]
