[Header]
2017-04-18 13:42:59,082 [1] ERROR ConsoleApp.LoggingExample [(null)] - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   在 ConsoleApp.LoggingExample.Foo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 99
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 106
   --- 内部异常堆栈跟踪的结尾 ---
   在 ConsoleApp.LoggingExample.Goo() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 112
   在 ConsoleApp.LoggingExample.Bar() 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 94
   在 ConsoleApp.LoggingExample.Main(String[] args) 位置 d:\work\实验室\Log4NetDemo\examples\net\2.0\Tutorials\ConsoleApp\cs\src\LoggingExample.cs:行号 60
[Footer]
